### ISSUE TITLE
楼主，RCTHtmlView帮忙下

### ISSUE THREAD

**Issue by 0xjunior168** [bawn/noder-react-native#1]
小白最近在使用react native做个cnode客户端练练手。由于使用react-native-html-view来渲染帖子详情的时候发现内容量一旦多就渲染慢，卡。看见楼主使用HTMLKit，AsyncDisplayKit，写了一个原生组件来调用，想借用这一块，能否描述下如何使用。谢谢。

**Comment by bawn** [comment]
@Mrlyjoutlook 

要用的话，需要把 Noder/HTMLNode 文件夹中的所有文件和 
RCTHtmlView.h 
RCTHtmlView.m 
RCTHtmlViewManager.h 
RCTHtmlViewManager.m

拖到你的 iOS 项目中，用 Cocoapods 安装 Texture(以前叫AsyncDisplayKit)  和 HTMLKit。JS 中怎么用就看 DetailRender.js 就行了。

其实你直接看这个项目就知道怎么用了

**Comment by 0xjunior168** [comment]
Thanks. 就是不知道会不会漏了哪些配置。

2017年10月16日 +0800 AM10:46 Bawn <notifications@github.com>，写道：

@Mrlyjoutlook<https://github.com/mrlyjoutlook>

要用的话，需要把 Noder/HTMLNode 文件夹中的所有文件和
RCTHtmlView.h
RCTHtmlView.m
RCTHtmlViewManager.h
RCTHtmlViewManager.m

拖到你的 iOS 项目中，用 Cocoapods 安装 Texture(以前叫AsyncDisplayKit) 和 HTMLKit。JS 中怎么用就看 DetailRender.js 就行了。

其实你直接看这个项目就知道怎么用了
